# .github/workflows/deploy.yml
name: Deploy to Yandex Cloud

on:
  push:
    branches: [ main ]  # или ваша основная ветка

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true  # подтягиваем тему PaperMod

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v3
      with:
        hugo-version: '0.155.2'  # ваша версия Hugo
        extended: true

    - name: Build
      run: hugo --minify

    - name: Deploy to Yandex Cloud
      uses: yandex-cloud/actions-yc-s3-deploy@v1
      env:
        YC_S3_BUCKET: 'burachevskiy.ru'   # Имя вашего бакета
        YC_S3_ACCESS_KEY: ${{ secrets.YC_ACCESS_KEY_ID }}
        YC_S3_SECRET_KEY: ${{ secrets.YC_SECRET_ACCESS_KEY }}
        YC_S3_ENDPOINT: 'https://storage.yandexcloud.net'
      with:
        args: --recursive --delete ./public/ /
